### ISSUE TITLE
[FEATURE REQUEST] time that gym has been holding

### ISSUE THREAD

**Issue by springjools** [RocketMap/RocketMap#1211]
I just wanted to put this here instead of in chat so that more people can see this:

I'd like to have a time showing with the -gi option that is how long the gym has been held with the current team. It would be useful which gyms usually hold for 2 mins and which ones hold for 5 days (yes there are those).

If more people are interested in this option I could work together to implement it, it's probably not that hard code-wise, but I imagine that it could be db-heavy.

**Comment by rlenders** [comment]
Is it even possible to see the time a gym has been held *in the game*?

**Comment by k4n30** [comment]
@rlenders no - but the idea is to log it in the database and upon refresh see if it has changed or not.  @springjools you would need to include what pokemon and what level they are to ensure that it's not taken by another team and quickly retaken by the originating team to ensure it's not a continuous time block

I've been looking for this too :)

**Comment by springjools** [comment]
Yes, true, but I would be happy with an 80% success rate. And what I want is to find the gyms that last long, don't really care if it's so accurate with those gyms that change ownership as often as tom cruise changes lovers :)

**Comment by jnovack** [comment]
> so that check wouldn't be so hard

That requires either a SELECT WHERE before your Gym UPSERT (to pull the status of the gym BEFORE upserting) -or- a log table of changes.

PERSONALLY, I prefer the log table of changes.  This way you get a full history of when things happened.

But the table would really have to be planned out to be useful.

```
timestamp, gym_id, team, prestige, pokemon_ids (delimited)
```

**Comment by aguita** [comment]
@jnovack I agree!  Logging the data into another table is a more efficient way of doing this.  I might get some time this weekend to start looking at this.   Is this something that we can offer to install a trigger on the database for people, or should we be implementing this in code?  I prefer the trigger method, but I understand that not everyone is using the same DB

**Comment by jnovack** [comment]
SQLite and mySQL have different `CREATE TRIGGER` syntaxes.

**Comment by deirdresm** [comment]
Doesn't mean triggers can't be used, just that the code would be slightly more complex.

Random thought:

A gym has likely "changed" hands despite being the same color if the previous top-tiered Pokémon is no longer in the gym and the lowest member of the gym is lower than the previous top-tiered one. I.e., if TeddySnorlax CP 2199 from trainer FooBar is no longer there, but there's a Jolteon of 1600-ish CP in there, then the gym has changed. If the bottom level of the gym is now higher, it's really hard to tell because TeddySnorlax may have been lost in a gym attack without the gym changing hands (if there were higher members added after the last scan).

The biggest question is how many assumptions do we want to make about what constitutes changing hands?

**Comment by springjools** [comment]
How about just checking if none of the previous members of the gym are still present?

**Comment by jnovack** [comment]
> How about just checking if none of the previous members of the gym are still present?

The following case could happen.

* CPs 1700, 1710, 1720 ... 1790 are 10-stacking a Gym.
* Scan Gym
* EnemyTeam knocks out 1700, 1710. (Level 8 Gym now)
* FriendlyTeam builds up to 10, adding in CP 1800, and 1810. (Level 10 Gym).
* Repeat until all 10 original members are knocked out.
* Scan Gym

At this point, the gym is completely different, but you don't know if it held, or if it was wiped.

> The biggest question is how many assumptions do we want to make about what constitutes changing hands?

This is exactly the correct question.  We can NEVER officially know.  Even if we scan every 10 seconds, FriendlyTeam could Max Revive and place the same (last) Pokemon back in before EnemyTeam decides who to throw in.  There's no real way to KNOW because we do not get a "To_Neutral" trigger.  So.. how many assumptions do we want to make?

**Comment by springjools** [comment]
True.

I think most people would use this function to map gyms that hold > 1 day or so, so it's not that critical if some 5 min gym transfers go unnoticed.  Imo we can make a lot of assumptions for performance's sake.

**Comment by jnovack** [comment]
> to map gyms that hold > 1 day or so, so it's not that critical if some 5 min gym transfers go unnoticed. 

It didn't hold for >1 consecutive day if it had a 5 min transfer.

**Comment by beccasafan** [comment]
Obligatory "Ewwww, triggers" comment.

😏

**Comment by deirdresm** [comment]
> How about just checking if none of the previous members of the gym are still present?

One of the issues (also with my comment above), some of the people in my area put the exact same mon in after the gym switches again.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
