### ISSUE TITLE
[Feature Request] Add the speed-up technique by ignoring common mons

### ISSUE THREAD

**Issue by Gallifery** [RocketMap/RocketMap#1297]
## Expected Behavior

I saw a post on Reddit that someone mentions a technique that by setting a list of pokemon that you don't care to catch, the API call to request their exact location can be skipped. With the scan radius of 200m, you can know what pokemons are in your 4 squares, ie. se,ne,nw,sw. And only by a scan that is accurate to 50m radius, you can get the location of the pokemon.  
https://www.reddit.com/r/pokemongodev/comments/5148q2/alpha_pickymap_faster_tracker/?st=it1pq1gc&sh=983c670b
## Current Behavior

I believe this technique is not implemnted as I haven't seen it mentioned.
## Possible Solution

Refer to https://www.reddit.com/r/pokemongodev/comments/5148q2/alpha_pickymap_faster_tracker/?st=it1pq1gc&sh=983c670b
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment

- Version used:
- Environment name and version (e.g. Python 2.7):
- Operating System and version (desktop or mobile):

**Comment by averylarry** [comment]
PR #1229 ??

**Comment by Gallifery** [comment]
PR #1229 tries to skip fine scanning by decoding the pokemon id and calculates which spawnpoint within the 200m circle could have spawned that pokemon.

The feature I request is to compare the pokemon names with the ones in a blacklist and simply do not perform a fine scan if all of them are in the blacklist.

**Comment by averylarry** [comment]
I think the misunderstanding is this -- #1229 WILL know the exact location.  A 50m scan is not needed in addition to the 200m.
If you are still interested then I guess I'll just say my opinion:
1) This is pointless in spawnpoint scanning.
2) If you are not using spawnpoint scanning, then you have no idea if a new pokemon will spawn 1 second after your 200m scan.
3) There is a finite amount of physical area that can be reasonably scanned with 1 account without greatly increasing your account ban rate.  You can only scan more area faster without excessive account bans by ... using more accounts.
4) In conclusion I can see some minor improvements in certain scanning scenarios but I personally wouldn't consider it worth the effort to code.

**Comment by Gallifery** [comment]
@averylarry 
1) This is pointless in spawnpoint scanning.
-- Why?
2) If you are not using spawnpoint scanning, then you have no idea if a new pokemon will spawn 1 second after your 200m scan.
-- I am using spawnpoint scanning, again, to point 1), why pointless in spawnpoint scanning?
3)There is a finite amount of physical area that can be reasonably scanned with 1 account without greatly increasing your account ban rate. You can only scan more area faster without excessive account bans by ... using more accounts.
--As I suggested in PR #990, the solution to scanned locations more scattered is to allow idling scan accounts. Maybe 5
4) In conclusion I can see some minor improvements in certain scanning scenarios but I personally wouldn't consider it worth the effort to code.
Well, I think the other way. 70m area is 1/9 OF 200 m area. The boosting factor can be a lot.

**Comment by averylarry** [comment]
1a)  With spawnpoint scanning, everything in the 200m nearby list WILL ALREADY HAVE BEEN SCANNED before it shows up in the sightings/nearby list.  There's nothing to skip.  Unless maybe you don't have enough accounts and your queue gets minutes behind (which can be fixed by more accounts).
1b)  #1229 WILL ACCOMPLISH THIS WITH A SINGLE 200m SCAN.  You would never skip any 50m scan location because 50m scans are NEVER done with spawnpoint scanning in that PR.

3)  Idling scan accounts is using more accounts just like I said.  More efficient/fancy/useful -- but it's really still the same point I made -- use more accounts.
4)  Again -- #1229 does this when you know spawnpoints.  (Beehive scanning when spawnpoints are unknown is a far different discussion.)

This is still just my opinion, and maybe I'm missing something.  I just don't see any goal that this will accomplish (at least to be worth coding).  The number of accounts you use is really the limiting factor in speed and area because account bans come from moving too fast/teleporting (at least that's a major reason).  Large scan radius doesn't change the fact that this is based on the real physical world but then there are computers deciding if your account moves faster than a human can.

I believe the real benefit from 200m scanning is implementing PR 1229 and using spawnpoint scanning and compressing the spawnpoints.  I have 419 spawnpoints in a small area.  Using a 50m radius I can compress that down to 251 scan locations.  Using 200m radius I can compress that down to 156 scan locations.  Fewer scan locations means I actually reduce the overall distance traveled (straight line from point A to point D because we don't need to travel to points B and C anymore).  I can actually now scan the same area with fewer accounts.  I can never scan any faster, because it doesn't get any faster than scanning a spawnpoint shortly after it spawns.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
