### ISSUE TITLE
Feature Request: Proper recognition of different spawn types

### ISSUE THREAD

**Issue by justj0sh** [RocketMap/RocketMap#1323]
## Expected Behavior

Basically correctly identify non-15 min spawns
## Current Behavior

Everything classified as 15 mins
## Possible Solution

This guy has it figured it out. Just need someone to port the code over: https://github.com/seikur0/PGO-mapscan-opt
## Context

Missing a lot of longer spawns

**Comment by Shentang** [comment]
But seriously, this should be #1 to implement, all pokemons are just 15min, while at least 10% is 30min..

**Comment by justj0sh** [comment]
No one wants to do it

**Comment by beccasafan** [comment]
It's actually something that we've started. It's just a big project. And api uncertainty has affected it. 

...and it's a huge change. ;)

**Comment by therealphaTT** [comment]
BUMPing this because the API will be cracked soon. I really wish I could still use mapscan but the captcha changes will render it unusable. It is seriously the best scanner. Some pokemon last an hour, some are hidden for 15 minutes and then come back for 15 minutes, and the spawn scanning uses a smaller amount of calls and uses less accounts. I could run a 5km circle with only 25 accounts! Catching each spawn within 5 seconds.

**Comment by FrostTheFox** [comment]
The captcha is being worked on, but not having a working implementation makes it hard to test and implement :)

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
