### ISSUE TITLE
[Feature Request] Clickable Buttons To Move To Areas On The Map

### ISSUE THREAD

**Issue by ChilliHam** [RocketMap/RocketMap#1344]
I think it would be a neat idea to have to option to add buttons to the bottom right of the map that will allow you to jump to coords to see what is in the area. 
I'm not asking to make it scan that area. This is mainly for people that have multiple areas being scanned and this will be an easy way to go directly to it.

For example, I'm scanning my neighborhood/my downtown/ a friends neighborhood.
It would be great to have a clickable button that will jump me to their areas on the map and see what is there.

**Comment by perzim1234** [comment]
+1
I would like this to, currently scanning 3 large areas with spawnscanning and using localtunnel for each places with fixed lcoation. If this works out I will only need one localtunnel site instead of three. 

Im not good at coding, but if someone is willing to write a simple code I can paste into map.html where I can set cords and name for button I will appreciate that.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
