### ISSUE TITLE
Sanitize/normalize/shrink server-client communication

### ISSUE THREAD

**Issue by SoonDead** [RocketMap/RocketMap#1348]
A large amount of pokemon data is fixed. A pokemon that has the ID of 16 is a Pidgey, it's rarity (whatever that means) is common, it's types are Normal/Flying. All of this information is already available in pokemon.min.json (which is requested on page load), yet for every pokemon all this information is sent. Even the color of a type is sent every time yet it is also fix.

Javascript is not that slow/independable. Querying a pokedex by id on the client would be no slower and the pokemons array in the raw_data response would be halved.

I'm not against clarity, but this seems a little too much.

If only the pokemon_id would be sent to the client, and the client side javascript had prepared functions for getting type data of a pokemon by id (or just simply an associative array of data with the pokemon id as key), it would have no real downsides I can think of.

What is the reason behind the current response being this detailed? Should I just simply try to refactor this?

**Comment by DiscoTim** [comment]
I agree this redundant data should be stripped out. The biggest issue though is what https://github.com/PokemonGoMap/PokemonGo-Map/pull/1303 is addressing.

a typical poke being sent to the client includes:

encounter_id:
disappear_time:
latitude:
longitude:
spawnpoint_id:
pokemon_name:
pokemon_rarity:
pokemon_types:

definitely name, rarity, and types are not needed to be sent to the client. if rarity used a system where the server determines what is rare based on previous data (or something else), then it would be, or need to be sent in a different way, but as it currently stands it isn't.

The client is currently using this data, but could be refactored so that it isn't.

This effects the webhooks as well, some web hooked apps may be relying on this, i don't know. so maybe it has to stay on the webhooks?

**Comment by SoonDead** [comment]
I think an external app would benefit from smaller calls as well but since it would break such apps (although very easy to fix), it could stay there for compatibility reasons (which I don't believe in on a develop branch).

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
