### ISSUE TITLE
Dump despawned pokemon into archive table for non-critical usage

### ISSUE THREAD

**Issue by justj0sh** [RocketMap/RocketMap#1358]
## Current Behavior

Workers/front-end deals with table containing data of entire running history resulting in significantly slower queries which would result in DB locks that clog up the queue
Stats page is generated dynamically and if someone likes to click the refresh button it can clog up the DB queue
## Possible Solution

Despawned pokemon get moved to archive table whether by cron job or db_cleaner thread
Stats/heatmap page should also be cached periodically from this archive table
Spawnpoint dumping will also come from this archive table
## Context

Most people keep old spawns for generating heatmaps and spawnpoint dumps
Data is not used for other purposes and is a gigantic deadweight
Will speed up front-end server by keeping the rows to the absolute minimum
If stats/heatmap page is cached periodically (again, either cron or thread that runs hourly or something), it would also free up resources for people with OCD that constantly refresh the page

**Comment by justj0sh** [comment]
This should probably go under the clean_db_loop function. Open to other ideas.

```
CREATE TABLE IF NOT EXISTS pokemon_archive LIKE pokemon;
START TRANSACTION;
set @N := (now());
INSERT INTO pokemon_archive SELECT * FROM pokemon where disappear_time < date_sub(@N,INTERVAL 24 HOUR);
DELETE FROM pokemon WHERE disappear_time < date_sub(@N,INTERVAL 24 HOUR);
COMMIT;
```

**Comment by averylarry** [comment]
Instead of an archive, what do people think about the opposite?  Leave things the way they are now and add a temporary table that only contains current information.  Adding information to the db would double because you would insert/upsert/whatever both the normal and the temp/current tables.  db_cleanup would simply delete information from the temp table that is no longer considered current.  Restarting the service could just truncate the temp/current table (or run a db_cleanup).

**Comment by aguita** [comment]
@averylarry Which table is the main map going to point to, the current table or the temporary table?  If it points to the temporary table, then I agree with you.  If it points to the current table, then I'd rather go with the concept of an archive table and clean the current table.

**Comment by averylarry** [comment]
I suppose the main map = fast = small current table.  You can add an option for the stats page to query either?  But really, I just had the concept of accomplishing this idea more like using a fast cache for current data instead of removing things into an archive database.  Just opposite sides of the same concept, more or less.

**Comment by jtp10181** [comment]
@averylarry It sort of goes both ways, if you have a temp current info table you make double writes to the DB. You would have to update the map and stats pages to use the new table (probably easy).

If you make an archive table you would need to update the spawn scanning mode to pull from both tables and most other things could be left alone.

I would say the gym and pokestop tables could be left, but the pokemon table is the one that needs something done to preserve the spawn data but archive old pokemon sightings for stat pulls only.

What if you only archived DUPLICATE entries from the same spawn point, keeping the newest one (to keep the spawn info in the table). Also you would keep anything newer than X days old. Might need special handling for the spawns that are greater than the standard 15x1h spawns.

I dont think I would want any of the old sightings older than week back, just dont want to delete the spawn point info from the table. You cant adjust the stats page to a custom date range so it doesn't do you much good. 

All my archival data is saved with pokelyzer.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
