### ISSUE TITLE
Spawnpoint amount is going up rather quickly

### ISSUE THREAD

**Issue by Shentang** [RocketMap/RocketMap#1456]
I've noticed that since the last spawn update my spawnpoint amount is going up noticeably quick - I mean, I had 7k pre-update, 14k just after the update, 29k (!) yesterday when I shut the scanner off to check something, and now I'm on 30,9k. I didn't change anything, I'm using -ss all the time, didn't scan any new places... 

Does anyone see the same behaviour?

**Comment by WalterMagnum** [comment]
Are you scanning from json or db?  If you are scanning from a db you could be getting duplicates.  That being said, I did notice an almost 2x increase in spawns immediately after the update.

**Comment by Darkknightz** [comment]
I wonder that if you export the spawnpoints to JSON and apply the compression in tools. How many will be left. Perhaps they applied some kind of jitter on time/loc ?

**Comment by Shentang** [comment]
>I wonder that if you export the spawnpoints to JSON and apply the compression in tools. How many will be left. Perhaps they applied some kind of jitter on time/loc ?

How can I apply compression?

>Are you scanning from json or db?

MySQL, didnt happen before the last update

**Comment by rodrgomes** [comment]
It's happening with me too... to calculate the spawnspoints this query is run

SELECT DISTINCT `t1`.`latitude` AS lat, `t1`.`longitude` AS lng, ((EXTRACT(minute FROM `t1`.`disappear_time`) * %s) + EXTRACT(second FROM `t1`.`disappear_time`)) AS time, `t1`.`spawnpoint_id` FROM `pokemon` AS t1 where ...

What is happening is that each spawnpoint is getting different timestamps for time.

That is what I get running the following query
select spawnpoint_id, count(*) from (SELECT distinct spawnpoint_id, ((EXTRACT(minute FROM disappear_time) * 60) + EXTRACT(second FROM disappear_time)) AS time FROM pokemon AS t1
) t2 group by 1 order by 2 desc limit 10;

+---------------+----------+
| spawnpoint_id | count(*) |
+---------------+----------+
| 94ccfab205d   |      155 |
| 94ccf0745ff   |      142 |
| 94cce555645   |      142 |
| 94ccf07035d   |       95 |
| 94ccfaa0a0f   |       90 |
| 94ccf015a6f   |       88 |
| 94ccf02fee9   |       86 |
| 94ccf0114f1   |       86 |
| 94ccfaa7583   |       85 |
| 94ccf000907   |       85 |
+---------------+----------+

**Comment by averylarry** [comment]
dump a spawnpoint file.
in tools\Spawnpoint-Clustering
Off the top of my head you need to run:
cluster.py spawndump.json -os compressed.json -r 60 -t 180
if you use jitter -r 60 is recommended, otherwise you can use -r 70 (that's the radius)  -t is basically seconds you're willing to be late.  The output will tell you directly how many you have.

You can use the compressed spawnpoint file with -ss

**Comment by Shentang** [comment]
Completed in 766.11 seconds.
11307 clusters found.
35.06% compression achieved.


Is that high?

**Comment by averylarry** [comment]
Depends on what you mean by "high".  32k spawnpoints have been compressed down to 11k.  That's really good, and certainly implies that you have a lot of spawnpoints with slightly different disappear times.  This is very likely due to the way that the code handles the different types of spawnpoints (it doesn't really).  That is being worked on.
You should use the compressed spawnpoint file you created.

**Comment by TheNewDarkOne** [comment]
Well another issue is that it still doesn't properly handle spawn point types either. it might treat one spawn point with two different times as two different ones, etc.

**Comment by toshioson** [comment]
I'm using MariaDB and for the spawnpoints already in it, there is no way to clean up the dup except rebuild it?

**Comment by averylarry** [comment]
The duplicates will just come back.  There is a plan for proper spawnpoint identification.  It is very likely that the duplicates will be cleaned up when that plan happens.  It's a major code change so don't expect it quickly.

**Comment by weizh888** [comment]
@averylarry Could you tell how to dump a spawnpoint file, compress it and reload it to mysql? Thanks!

**Comment by averylarry** [comment]
You don't reload it to mysql.  You just use the compressed file as the locations to scan.

runserver.py -ss --dump-spawnpoints pickafilenameyoulike.json
Tools\Spawnpoint-Clustering\cluster.py -os pickanewfilenameyoulike.json -r 60 -t 180 thefirstfilenameyouused.json
runserver.py <all your normal command line options> -ss thenewfilenameyouused.json

**Comment by shockler** [comment]
@averylarry Hi, what is the point to use that Clustering Tool? I never use it before, can you explain it?

**Comment by PhDeez** [comment]
@shockler 
The Clustering Tool allows you to cluster spawnpoints together so you can scan 1 location 1 time and get multiple Pokemon on your map from that one scan.  You specify the distance (-r 60 = radius of 60 meters of each other) and time (-t 180 = locations together within 180 seconds = 3 minutes).  This makes spawnpoint scanning much more efficient since you don't have to scan that one point 5 times for 5 pokemon, instead you scan it within 3 minutes and get all 5 pokemon.

If you have jitter enabled, (-j) keep your radius at 60m.  If you don't, you can push it up to 70 max (I go with 68) and 120s since that extra minute determines if I can get to a location or not.  It all depends on how far out you're scanning, and whether you're scanning for yourself, or others too.

**Comment by shockler** [comment]
Wow, I did read this PR before but I forgot it, thanks so much ^^, I will try to use it now.

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
