### ISSUE TITLE
[Feature Request] Store account names and passwords in database

### ISSUE THREAD

**Issue by foltincsaba** [RocketMap/RocketMap#1482]
## Expected Behavior

I would like to handle the accounts more easily.
## Current Behavior

I'm running a beehive -ss can with 18 instances. Each instance has different number of workers between 4 to 22. Each instance has its own .csv to pull accounts from. Each .csv has about twice as much extra accounts for account swaps.
It's very hard to track which account is banned/captcha-d. And even if I can, it's very tedious work to stop the scanner, open each .csv and replace those accounts.
## Possible Solution

We should store accounts in a data table. Each instance should request free accounts from the table when needed and mark them as used. Captcha-d and banned accounts could also be marked in the table. Teleporting problem could be handled by having a column in the database that shows which instance (status_name) used it and only that instance could use this account (or another account with NULL value in this column) again. This column should be NULL-ed each time the webserver starts.

This approach has a lot of benefits:
- You need less accounts, because each instance swapping from the same pool (you don't need a pool for each instance separately)
- You could add accounts to the database on the fly (while the map is running)
- If the accounts that need captcha to solve is marked in the database then this information won't get lost when you restart the map. So the program doesn't have to try connecting to the server with them again and get 0/0/0 results.
- Banned accounts can be found much more easily

**Comment by luannpeixe** [comment]
The only problem is that an instance can be very distant from each other and result in a teleporter, then bringing several softban.

**Comment by KoertJanssens** [comment]
@luannpeixe We could save the location and time of last scan in the table!

**Comment by Arengo** [comment]
@KoertJanssens I like this idea, since it is coherent with the new speed limit pull request. However, I am sceptical about storing account name and passwords in a database which might be easy to access through web - I would love to see the reCaptcha token though and even make them public.

**Comment by crckdns** [comment]
I've had the same idea today at work.. glad I'm not alone with the db thingy..
just add new columns like banned, captcha and very important field: origin/bind area which is for example linked to the -sn argument~ so the mainworker will know what accounts are belong to him :)

**Comment by huanga** [comment]
Sounds similar to the idea I shared in #1147 ?

**Comment by Maersko** [comment]
Sounds awesome, would really love this as I was soon to setup with CSV. But this would be so much better.

**Comment by mew905** [comment]
"select next account by distance, not time"

With DB focused accounts, it would theoretically work great with a speed limiter and even multiple cities. If select account by distance can be implemented and merged in combination with a basic speed limiter, it would, in theory, produce a decently efficient spawn scan while obeying niantic's "rules".

something like this:
If ((account.lastloc-spawnpoint.loc)/(account.lastscan-time.now)) > args.speed_limit: spawn new account

Maybe even compare the lastscan-time.now to the SD, and even max_delay so if it would arrive, say, 2 minutes late, it'll still scan it. (clearly would stack with spawnpoint compression).

Then no more need to separate cities using json data or separate databases, it should be able to dynamically allocate them so long as you have an abundance of spares :). Let users scan their own locations like FPM does (or even have an unlocked position map on a private url/port), and the code should automatically start spawn scanning that area indefinitely if it's doing -ss from the database. This excites me!

I've tried doing a "hot potato" implementation that would achieve a similar effect, but rather than selecting by distance, a worker would grab from the queue, see if it can make it in time, and put it back if it couldnt while grabbing the next one. This would work much better.

**Comment by evenly-epic-mule** [comment]
@mew905 
yep I tried that first, but then i noticed that at the time the account is selected the thread doesn't know which location is going to be scanned next

but if you want fork my repo and add support :)

**Comment by mew905** [comment]
yeah that's what essentially stopped me with my hot potato, with its current implementation, I was attempting to use a deque to grab the next item, check it if it can get there in time within a speed limit, if not, it'd place it back on top, rotate and grab the next item then rotate back (so next worker can check the first item to see if it's close enough). Problem was after about 5-10 minutes ALL of them started reporting they were too far. My guess is as the queue gets rotated, the other accounts are grabbing out of order at the same time.

The queue is already built when the accounts are made, at least initially, but there are two problems:
1: Without deque, there's no way to add items back to the top of the queue (unless my understanding is wrong and the queue is built from the bottom up).
2: the main queue that all the workers grab from only "refills" when it's empty (at least I think thats how it works, I'll have to recheck the code). If it can keep adding to the queue as it gets used up it would be ideal, problem is when a worker grabs it to check it, the main queue could already fill it in. Not a big deal with only a few workers, but imagine 400+ workers fighting over that queue.

**Comment by evenly-epic-mule** [comment]
the other idea would be pre calculated paths (maybe even over the googlemaps api or even with bike or car)

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
