### ISSUE TITLE
Using Spawn Clustering tool to find locations from where many pokestops are within reach

### ISSUE THREAD

**Issue by edgarborja** [RocketMap/RocketMap#1490]
Would it be possible to use the Spawnpoint Clustering tool, with some modifications, to find the spots where 2 or more pokestops are reachable from a single location?

If so, could someone more experienced give some pointers on how to achieve that?

Thank you.

**Comment by Arengo** [comment]
Easiest way would be to extract them like the Pokémon spawnpoints into a similar structured .json and let it run through the Tools->Spawnpoint-Clustering code.

**Comment by edgarborja** [comment]
Thank you Arengo. Is 40m still the maximum range? I think there was a change but I'm not sure.

**Comment by PhDeez** [comment]
@edgarborja No, take a look at the README in the Spawnpoint folder.  The max range is 70m, so go with 65-68m so you don't have to get exactly in the middle.  If you're actually walking it instead of transporting, use a time of like 7-12 minutes (instead of 1-2 minutes) since based on your idea is you'll be there anyways, right?

**Comment by drallieiv** [comment]
@Arengo if you use clustering, you end up with a single SP instead of a group, but how do you know how many there are at each grouped SP ?

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
