### ISSUE TITLE
[Feature Request] Send webhooks from separate thread directly from DB

### ISSUE THREAD

**Issue by pir2** [RocketMap/RocketMap#1500]
## Expected Behavior

Ability to grab data from database and send to webhook instead of running it as part of searcher thread
## Current Behavior

Each searcher sends it's own pokemon to the webhook
## Possible Solution

Implement an option to run a thread that periodically grabs pokemon from the database and sends to webhook
## Steps to Reproduce (for bugs)

My ugly amateur python code that sends pokemon to a webhook.  Uses step-size to select area to grab pokemons from.  Also option to only send specific pokemon_id's to the webhook.

[https://github.com/pir2/PokemonGo-Map/tree/webhookdb](url) 

I would submit a PR, but my code sucks and would require a lot of rework.  Putting it here so someone with more experience can submit a proper PR.
## Context

I run the searchers on different computers for proxy/ip reasons and it would be convenient to just have one webhook thread that checks for new pokemon and sends to a webhook.  The solution will cause a delay between finding new pokemon and sending it to a webhook, but such is the cost of convenience.

It also causes additional reads to database, but seems to run ok on MySQL

**Comment by mew905** [comment]
Personally I'd like to see the webhook come from the map.js side and replace the in-map notification code. While webhooks on the back end are great if it's just one user scanning a pre-defined area (and staying in said predefined area or having the search follow you) or many users with a pre-scanned small city (~50 sq km), it fails when you have hundreds or thousands of users, and multiple locations/cities. Webhooks from the front end would allow multi-user maps to send webhook data instead of notifications. This is the only way I can think of that notifications will work universally. Currently they're hit or miss, if you open a link in the facebook browser (doesn't allow location OR notifications), or have an iPhone/iPad/iPod (etc), web based notifications don't work. Even with Chrome for Android and default browsers it's hit or miss. With webhooks on the front end the notifications can follow any/every user, allow them to select which pokemon they want to be notified of, and even choose their own notification distance by simply zooming in and out (maybe hard code it to a maximum since texting via twilio and PokeAlarm for many cities would cost a fortune). The tradeoff? Multiple webhook requests for the same pokemon & increased end-user data usage.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
