### ISSUE TITLE
Same gym gets processed by several workers at once(?)

### ISSUE THREAD

**Issue by birdstream** [RocketMap/RocketMap#1615]
## Expected Behavior

When a gym changes, only one worker should process it

## Current Behavior

It seems that whenever a gym changes, all workers in range (1km) starts processing it. Watching the ps output in the terminal, i can see several "processing details..." happen at the same time. I doubt that several gyms get battled simultaneously here in my small town at 2 AM ;) I suppose this could have some impact on scanner performance...

## Possible Solution

Maybe update the last_modified column in the gym table prior to getting details? Or raise some flag to tell the other workers this gym is being processed so they can carry on.

**Comment by mew905** [comment]
this is why I run -ng -nk and have a dedicated -np worker. That said, I dont think it'd be difficult to add something like "if gym_id not in parse_gyms then:" and proceed to parse it. Gyms, stops and scanned locations are all typically updates rather than inserts, and to prevent DB locking I had to get rid of all 3, gyms and stops can be parsed by multiple workers at the same time and then they sit there waiting for each other to finish. If this upsert is unsorted it potentially causes deadlocks, if it is then it's just subject to regular lock timeout errors. DB performance definitely plays a part though and the above would *only* work if all the workers are under the same account overseer, and may not work with db-threads > 1.

**Comment by drallieiv** [comment]
I think this is what causes #1683

Even with a dedicated gym thread, the circles do overlap, so 2 workers of the same process can do it too.

**Comment by ifhbiff** [comment]
But rather than deal with all the timing issues of the multiple workers, can't this be fixed (at least visually) with a DISTINCT on the pull of the data for the pop up?

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
