### ISSUE TITLE
[Feature Request] update pokemon rarity using % spawned in map area

### ISSUE THREAD

**Issue by BrownSlaughter** [RocketMap/RocketMap#1675]
Rarity is affected by local area for example Mr.mime is "very rare" even though I get a around 200 a day

## Expected Behavior

extract the % of spawn on map in the last day "Seen: 327 (3.6758%)" and change the rarity accordingly
for example 
Pidgey Seen: 1,579 (17.7496%) so 10-20% could be common
Lapras Seen: 1 (0.0112%) so less than 0.02% could be ultra rare

then edit the rarity in pokemon.json or have it database based

## Current Behavior

currently uses a static rarity that is not accurate for local areas

## Possible Solution

change the pokemon rarity dependany on local spawn rates

## Context

an example is a "rare" Geodude vs a "very rare" Mr.mime
Geodude  (0.3934%)
Mr. Mime (1.1129%)
It seems out of place I see 3x as many "very rare" than I do a "rare"

Changing this dynamically would solve this

**Comment by TheNewDarkOne** [comment]
This has been suggested before but it's still subjective to where you actually scan. For example I could spend 9 days out of 10 scanning near my house and 1 day out of 10 scanning by river where i travel to from time to time. so my percents will show water biome pokemon as MUCH rarer than they actually are since i only spent 10% of my scan time in a water biome.

**Comment by BrownSlaughter** [comment]
I usder stand that but for those of use that scan a specific area all the time it would be a really useful and if it got the rarity from the last day on stats page it would adjust accordingly for those that move their search location day by day

**Comment by MarkoHess** [comment]
I like the idea, but i would suggest to gather the data from the spawns in your hex grid for a rarity priority. When i start the -speed scan version it shows how much it has covered from the initial scan. If it is let's say >90% it could use the spawn data it collected, or not? Because after starting up a new/old speed scan it shows me how many spawnpoints are inside my hexgrid, so the spawnpoints are already loaded depending on my search grid and not the whole database.

**Comment by SiteEffect** [comment]
This is still in need, even when you fail certainty for biome Pokémons you get at least Very Rares and Ultra Rares better reflected.

**Comment by sebastienvercammen** [comment]
Feature requests: http://vote.devkat.org. There's a relevant open request called "Dynamic rarity for pokemon based on public webhook data".
