### ISSUE TITLE
scan is bugy and the time is not right all pokemon 52min o.O

### ISSUE THREAD

**Issue by Meik1712** [RocketMap/RocketMap#1693]
Hello at All

All Pokemon is (52 Min) what is this for the bug

My Config in Pic:

![bug](https://cloud.githubusercontent.com/assets/1857535/21778582/42f76d4a-d6a4-11e6-9578-bd9b9139ef3d.png)

Help me :(

**Comment by LucidLunatic** [comment]
Similar problem, except I'm seeing all Pokemon appear with under a minute- around 50 seconds.

**Comment by birdstream** [comment]
@Meik1712 First off, you should keep your gmaps key secret ;) Secondly, it's not wise to run with such low scan-delay! You will be breaking speed limits, and possibly your account will be bot-flagged really fast. If you want to cover an area faster, consider using multiple accounts instead. The reason you see despawn times less than one minute is because the scanner has yet to find the TTH (time-to-hide) for that particular spawnpoint. Until TTH is found, the map will not make any assumptions regarding despawn time. Niantic changed the behavior on this a while ago. Before TTH was given at any moment, but now it's not revealed until just before the pokemon despawns. So the map will need to run the same area for a while to learn all TTH's...

**Comment by LucidLunatic** [comment]
Thank you very much, Joakim. I was just about to post an update. You are
100% correct. Once it had been running over the area for some time the TTH
was updated and appears accurate. Incidentally, what is your recommended
scan delay? I have been using 20-30 seconds.


*LUKE MASTALLI-KELLY*

FOUNDER AND CEO *• *STARFISH ENTERPRISE, LLC



T. 301-807-8334 *•* info@starfishenterprise.net

5912 Turnstone Ct Wilmington, NC 28409

http://starfishenterprise.net

**Comment by birdstream** [comment]
@LucidLunatic i think the default 10 secs would work. But i'd say 12 secs just to be on the safe side, so you won't miss spawns (speedscan scheduler takes a ~12 sec delay between neighboring locations with default speed limit at 35 km/h)

**Comment by LoStBoYz** [comment]
I am also encountering the 52 mins error as well. The pokemon will despawn way before the 52 mins is up.
For example, yesterday a Chansey was manually sighted at 11.47pm, The scanner sighted it at 12.09am and gave a 52mins despawn time. I believe its a 1 hour spawn, but the spawning time is wrong.
I'm currently using 0.51 with sd 30. I have never seen this phenomena using when using 0,45 with the same settings.

**Comment by WalterMagnum** [comment]
Read the docs...

> What

 should I set scan delay (-sd) to?

With the default speed limit of 35 kph, scan delay isn’t needed. It takes about 12 seconds to get to a neighboring location, which is sufficient delay. If you include an -sd lower than 12 seconds, it won’t have an effect. If you use a -sd higher than 12, it will decrease the amount of scans your workers can do.

>

**Comment by LoStBoYz** [comment]
Um higher SD will result in missing pkm and slow detection. We are talking about 52mins detected spawns. If it's missing I wouldn't know about it in the 1st place. I also noticed the 1 hour spawns are unreliable. Some the Despawn time is much less. I have A TTH of 99%.....

The reason why I'm using SD 30 is to reduce captcha and still hit 100% spawn reach, this is very much depends on your spawn count in the scanned area.

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
