### ISSUE TITLE
icons-sprite.png missing and bug in maps

### ISSUE THREAD

**Issue by Meik1712** [RocketMap/RocketMap#1777]
![icon-sprite-missing](https://cloud.githubusercontent.com/assets/1857535/22397934/74b1d4c8-e57d-11e6-83e5-0e14bb3cbf11.png)
![sprite bug](https://cloud.githubusercontent.com/assets/1857535/22398018/fcf33f38-e57e-11e6-8972-3322b200f213.png)

**Comment by sebastienvercammen** [comment]
The "missing" error is not a bug: copyrighted content (such as icons & spritesheets) have been removed from the repository. Details about this change were also documented on our Discord, in the #announcements channel.

The second image is because you're using a spritesheet with the wrong dimensions, or your browser has cached an old version of it (and you should clear your browser cache).
