### ISSUE TITLE
Map speed scan fails on left side

### ISSUE THREAD

**Issue by dajoker17** [RocketMap/RocketMap#1801]
## Expected Behavior

The workers seem to have issues on the left side of the map when completing an empty area.  Generally restarting the instance multiple times (10+) will resolve the issue as some of the bands seem to be "given up" on each restart.
Workers never seem to return to the left side to complete the initial scan
Leaving the map running never completed the initial scan to 100%

## Current Behavior

When starting an instance:
2017-02-03 06:08:24,762 [ search-worker-6][    schedulers][    INFO] Step 665 failed scan for 3 times! Giving up...

Then the next time its started the same band:

2017-02-03 06:40:40,617 [search-worker-17][        search][    INFO] Scanning step 665 for a band.
2017-02-03 06:40:41,335 [search-worker-17][        models][ WARNING] Bad scan. Parsing found absolutely nothing.
2017-02-03 06:40:41,335 [search-worker-17][        models][    INFO] Common causes: captchas or IP bans.
2017-02-03 06:40:41,351 [search-worker-17][    schedulers][    INFO] Step 665 failed scan for 3 times! Giving up...

## Steps to Reproduce (for bugs)

start a scan with the left of the map on an empty area (no gyms, stops, mon, or nearby)
leave running and initial scan will never complete.
restart the instance and see some empty bands complete.

1.

![image](https://cloud.githubusercontent.com/assets/25513982/22564940/8091bb26-e9da-11e6-8b83-91d71f2bf8db.png)
![image](https://cloud.githubusercontent.com/assets/25513982/22564957/983e1c6a-e9da-11e6-9d11-215dc0ea9bb3.png)

2.
3.
4.

## Your Environment

* Version used:
Current version and I have noticed it in the last many pulls.
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
Windows server 2012.

**Comment by equatebrand** [comment]
I've noticed the same thing. I cleared all my databases and ran it again and it's again did this, also on the last several pulls, using CentOS.

**Comment by birdstream** [comment]
Why scan such a large empty area, though?

**Comment by TheNewDarkOne** [comment]
speed scan is really bad in rural because it still assumes empty means bad and spends so much time retrying that if you don't have enough accounts it actually doesn't get anything done and starts not doing other areas. I think you can fix this with more accounts I've noticed. I also think it can be improved somewhat by changing the give up count from 3 down to just 2. or even 1 if you are confident you're settings are solid and avoiding soft ip bans. Then speed scan will spend a lot less time wasted aggressively rescanning dead zones.
