### ISSUE TITLE
Small rounding bug causing small number of speedscan bands to be continually retried

### ISSUE THREAD

**Issue by myntath** [RocketMap/RocketMap#1898]
## Expected Behavior

Once a band in a speedscan is complete speedscan no longer checks that band.

## Current Behavior

In a very small number of cases (for me 2/3200) speedscan rechecks certain initial bands repeatedly due to a rounding error.

This occurs in find_in_locs in models.py
An example of the bug from practice is:

 loc = (-38.37464429678964, 142.52190528050016, 32.414771538063)
and locs includes:
{'-38.3746442968,142.52190528': {'band2': 2853, 'band3': 3455, 'band1': 2053, 'midpoint': 21, 'longitude': 142.5219052805, 'band5': 1237, 'width': 118, 'last_modified': datetime.datetime(2017, 3, 2, 2, 41, 16), 'done': True, 'band4': 589, 'latitude': -38.3746442967896, 'cellid': u'6acd4df1c33a5c93'}}
will give key = '-38.3746442968,142.521905281'

This cannot be found in locs because of the extra decimal (528 vs 5281 on latitude) and so an empty band is returned instead of the complete band.

## Possible Solution

I am struggling to come up with a solution for this and would appreciate comments. I don't understand how the rounding works, in most cases the rounding is correct.

## Steps to Reproduce (for bugs)

1. Scan a large number of points
2. Monitor which items are being added to bands
3. Notice that some of those items are actually complete.

## Context

Even though I hit 100% scans complete I keep scanning for initial bands.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
Ubuntu, MySQL

**Comment by myntath** [comment]
Ok so a bit of digging this seems to be a python problem with format and floating point numbers. 

e.g. '{}'.format(142.5219052805) = 142.52190528

I don't think I know enough about python to know the best way to fix this.

**Comment by TheNewDarkOne** [comment]
I wonder if this is what's happening with me here https://github.com/RocketMap/RocketMap/issues/1897 I'l have to look more closely to see what's happening. but I know after 3 days it should have LONG given up on these hand full of bands. All I know I do see in mine is that it thinks they are all 100% bad scans, but that's because they are in ocean, there are no pokestops gyms or nearby there so of course scans find absolutely nothing. However the 3x retry code should eventually flag it "stop looking here". it does not. after 3x it puts back in queue and checks it again at attempt 1 mere minutes later. and never ever ever stops.

**Comment by rocketrobot99** [comment]
I have added a commit to PR #1900 which should fix your problem. It may also fix issue https://github.com/RocketMap/RocketMap/issues/1897

**Comment by sebastienvercammen** [comment]
Fixed in #1900.
