### ISSUE TITLE
avoiding captchas with random

### ISSUE THREAD

**Issue by Chipipablo** [RocketMap/RocketMap#1916]
Hi, 

I think we should consider more the introduction of random numbers between interval values in variables like scan-delay or the distance between scans in beehive. This would give a less robotic behavior to Niantic.

Regards

**Comment by SiteEffect** [comment]
Regarding captchas, this is no solution because either you have captchas simply being on .45 or you don't have them being on hashing. Regarding the general appearances of our workers in comparison to legit accounts? Yeah, tell me how many kilometres are in between each catch you do with your workers.

**Comment by Obihoernchen** [comment]
Scan delay is already random for SpeedScan because of speed limit and spawn points.

**Comment by sebastienvercammen** [comment]
We're already doing what's necessary to make it possible to run RocketMap. This isn't a specific request, it's a long-term goal.
