### ISSUE TITLE
Status page setTimeout() added whenever 'Group workers' is toggled

### ISSUE THREAD

**Issue by EagleWorks** [RocketMap/RocketMap#1929]
## Expected Behavior
When toggling 'Group workers', only the display of the page should change, not the number of times the page is refreshed.

## Current Behavior
When toggling 'Group workers', updateStatus() is called.  This also adds another window.setTimeout(), causing each refresh to be called an additional time for every toggle.

## Possible Solution
clearTimeout(), but that would require it to be stuck in a variable first.  Alternatively, separate the setTimeout() from updateStatus().

## Steps to Reproduce (for bugs)
1. Open /status
2. Hit F12 and check the Network tab to see when new data is loaded.  Keep an eye on the number of requests (Chrome), it should increase by 1 for each data load.
3. Go to the settings menu, and toggle "Group by workers"
4. The number of requests now increases by 2.
5. Toggle "Group by workers again", now the number of requests increases by 3.
etc.

## Context
This affected me more when the status page was updating as fast as it possibly could, already straining some browsers (FireFox, for example), exacerbating even further.  
I was trying to address that when I noticed this separate issue.

## Your Environment
RocketMap + FireFox / Chrome.  Did not test IE/Edge/Safari.

**Comment by neskk** [comment]
This can be easily fixed, good catch ;)
My first thought is simply removing updateStatus() from `$('#groupbyworker-switch').change(...)` because updates are already regularly coming in, we don't need to call updateStatus() again... This will probably make the status page to be rendered empty for one second at most (or until loadRawData returns), but this could also happen in the current implementation so I think it shouldn't be a problem.

**Comment by sebastienvercammen** [comment]
Fixed in #1806.
