### ISSUE TITLE
"Success: 0 (0.0/hr) | Fails: 0 (0.0/hr) | Empties: 0 (0.0/hr) | Skips 0 (0.0/hr)" in gyms-only scanning configuration

### ISSUE THREAD

**Issue by redking974** [RocketMap/RocketMap#2012]
## Expected Behavior
I use practically the same "gyms-only config" that I used 1 month ago, to launch a gym scanning during the night (when I don't need to scan Pokémons on my local map). I just made modifications with the new .example (like remove no-search-control: true and fixed-location: true) but not major modifications about scanning-values.

## Current Behavior
After 8 hours of running, number of scans remains to 0 (no success, no fails)

## Steps to Reproduce (for bugs)
The log :
https://mega.nz/#!24xAQBSa!ZQK1MnnWwP53xVubn3JB6D6un5ZsEcfbPTg_SXuMP0Q (10 MB file, all the 8 hours of logs)

The config :
```
# Required settings
###################

gmaps-key: XXX
auth-service: ptc
username: XXX
password: XXX


# Common settings
#################

host: 0.0.0.0
port: 5001
hash-key: XXX
accountcsv: accounts.csv
location: 44.84210020580348, -0.594048501807265
step-limit: 45
scan-delay: 30
no-pokestops: true
#no-gyms                        # Disables gym scanning (default=False)
no-pokemon: true
print-status: status
status-page-password: XXX
#captcha-solving                # Enables captcha solving. (default=False)


# Database settings
###################

db-type: mysql
#db:                            # Database filename for SQLite. (default='pogom.db')
db-host: 127.0.0.1
db-name: XXX
db-user: XXX
db-pass: XXX
db-port: XXX
#db-max_connections:            # Max connections (per thread) for the database. (default=5)
#db-threads:                    # Number of db threads; increase if the db queue falls behind. (default=1)


# Search settings
#################

altitude: 15
altitude-variance: 5
use-altitude-cache: true
workers: 30
kph: 15
bad-scan-retry: 2
#skip-empty                     # Enables skipping of empty cells in normal scans - requires previously populated database. (not to be used with -ss)
#min-seconds-left:              # Time that must be left on a spawn before considering it too late and skipping it. (default=0)
gym-info: true


# Account rotation
##################

login-delay: 5
login-retries: 5
account-search-interval: 15
account-rest-interval: 90
#max-failures: 5
#max-empty: 15


# Pokemon IV (Only use one of the filters below)
############

encounter: false
encounter-delay: 2
high-lvl-accounts: accounts-high-level.csv
enc-whitelist-file: enc-whitelist.txt


# Webserver settings
####################

locale: fr


# Status and logs
#################

stats-log-timer: 30
status-name: Arènes


# Misc
######

verbose: Log_Arenes.log
#very-verbose                   # Like verbose, but show debug messages from all modules as well.
                                # Optionally specify file to log to like above mentioned. (default=False)
#no-version-check               # Disable API version check. (default=False)
version-check-interval: 3600
#mock:                          # Mock mode - point to a fpgo endpoint instead of using the real PogoApi,
                                # ec: http://127.0.0.1:9090 (default='')
```

## Context
I've tried to launch a gym-only scan during the night, because I don't scan them during the day to preserve my hash key requests.

## Your Environment
* Version used: last update the 1st may 2017
* Environment name and version (e.g. Python 2.7): 2.7.13
* Operating System and version (desktop or mobile): W10

**Comment by michikrug** [comment]
Without looking in your log:
You have set an account-search-interval of 15secs. That can't work well.

**Comment by pokemaster974** [comment]
Hi, I've already use this value for my gyms-only config, and I never saw errors from RM until recently. But maybe something have changed about this parameter and that's why I got 0 scan now.

For me, it was the delay before a new account launch a research. As I plan to launch this config when I go sleep, I don't search a fast config, that's my reason to setup RM thinking to launch a new search only each 15 seconds.

What new value do you recommand for the asi ? Is it too high or too low ?

Regards.

**Comment by redking974** [comment]
Hi, I've already use this value for my gyms-only config, and I never saw errors from RM until recently. But maybe something have changed about this parameter and that's why I got 0 scan now.

For me, it was the delay before a new account launch a research. As I plan to launch this config when I go sleep, I don't search a fast config, that's my reason to setup RM thinking to launch a new search only each 15 seconds.

What new value do you recommand for the asi ? Is it too high or too low ?

Regards.

**Comment by michikrug** [comment]
No.
The account-search-interval tells the scheduler, how long an account is used without resting.
That means, if you set it to 15 secs, the account will only be used for 15 seconds and then removed from the list for the given account-rest-interval (for you 90 sec).

You can see this in the log: -> Account xxx is being rotated out to rest.
This message happens in you log every 5 seconds.
With that, all your accounts are just resting all the time. They log in (takes some time) and are already removed from the active list since the 15secs have passed.

So you can set it to a way higher value. E.g. 7200 (2 hours). I even use 12 hours (43200).

What you mean is the scan-delay parameter, which is using a default of 12 secs.

**Comment by redking974** [comment]
Ok, I just try. I've commented the line and launched RM. It have scans now. I don't know if it's better to let it commented or if I have to setup a value like you explained me juste above.
Thanks for the reply @michikrug and sorry for the inconvenience. I close my issue.
Regards
