### ISSUE TITLE
Notifications not working in most mobile browsers

### ISSUE THREAD

**Issue by dsorc** [RocketMap/RocketMap#2061]
## Expected Behavior
Notification received when pokemon is in view
Pokemon jumping
Pokemon tapable to see its details

## Current Behavior
Notification is not received (notifications accepted when accessing map the first time)
Pokemon not jumping
Pokemon is not tapable to see its details

## Possible Solution
Is there a browser setting affecting this?

## Steps to Reproduce (for bugs)
Enable notification for a pokemon type, reload page.
No notification.

## Your Environment
Android

Affected browsers:
- chrome
- opera
- samsung internet (previous version worked)

Still works in:
- firefox

**Comment by mspitzbarth** [comment]
The problem is that RM use Notification, this function is deprecated in most Mobile Browsers now.
https://github.com/RocketMap/RocketMap/blob/develop/static/js/map.js#L1590

![image](https://cloud.githubusercontent.com/assets/19345417/26673523/7768ef98-46bd-11e7-8fa6-f2af7e66ab3d.png)


So you also get a JS Error. You need a Serviceworker now, on desktop this works fine without a Serviceworker. https://developers.google.com/web/fundamentals/getting-started/codelabs/push-notifications/

I use this plugin on my Map.

https://nickersoft.github.io/push.js/

**Comment by dsorc** [comment]
I understood why it's not working.
But not how to make it work.

Do I need to install a plugin in my browser, modify the RM code, or... something else.

**Comment by mspitzbarth** [comment]
You need to modify the Rocketmap code and register a serviceworker on the line i posted above

**Comment by sebastienvercammen** [comment]
Instead of recommending that people edit their own code (which will inevitably lead to problems), we invite you to open a PR with a possible fix.

In the meantime, I've flagged the issue and someone from RM's PR team will pick it up as we work through some more important priorities, unless someone else wants to have some fun implementing it and opening a PR.

**Comment by Qualimiox** [comment]
The worse part of this issue (aside from them not working) is that setting notifications on mobile may result in different Pokemon being hidden from the map completely. Users set up notifications and suddenly the entire map is almost empty, the only fix is to delete all notifications and reload the map.
