### ISSUE TITLE
Shown spawnpoints are retrieved from Pokemon table instead from spawn points table

### ISSUE THREAD

**Issue by JoseLSegura** [RocketMap/RocketMap#2099]
I was trying to restore the old spawnpoints from a backup DB, when I realized that, even when I delete all the spawn points from the current DB, the interface is able to show the spawn points.

I read the code a little and I think that the show spawn points in the web interface are retrieved from the pokemon table, instead from the spawnpoint one.

I think that with the probable incoming changes in the game, with some spawn points migration, it will be better to retrieve the spawns from its own table instead from the pokemon database.

To reproduce it (assuming MySQL DB)

1.- DELETE FROM  scanspawnpoint;
2.- DELETE FROM scannedlocation;
3.- DELETE FROM spawnpointdetectiondata;
4.- DELETE FROM spawnpoint;

Then, launch a web server and enable the spawn points: you will see a lot of spawns, even with that tables empty

**Comment by jagauthier** [comment]
Unless there's a technical reason why, and I don't know what it is, you're probably right.  Reducing access to the pokemon table is good for performance as well.

**Comment by joselsegura** [comment]
I totally agree. I'm not an expert on data bases, but the Pokemon table is growing continuosly while the spawnpoint database is created when performing an initial scan and it doesn't change for "the rest of the life" of the map.

If nobody points a technical reason to do this, maybe I can create a PR, because I read that they are using a ORM that is or is very similar to SQLalquemy, and I have a few experience with it (at least, I know it :-D)

**Comment by friscoMad** [comment]
Should be fixed by #1948
