### ISSUE TITLE
RocketMap burns through accounts in 1h

### ISSUE THREAD

**Issue by PeshBG** [RocketMap/RocketMap#2246]
Hello,
since a few days rocketmap burns through my accounts withing just one hour.
i get bad scans on 90% of the instances i run(12 out of 15)

The accounts itself i have tested and they are also not seeing nor gyms nor pokestops. any ideas?

**Comment by daniel-mitran** [comment]
Yes. 
Have you activated --pokestop-spinning ?
If you use fresh accounts it's absolutely necessary.

**Comment by PeshBG** [comment]
no. i will try. i rolled out old accounts and they seem to be unblind

**Comment by sebastienvercammen** [comment]
This issue is very likely to be related to user error.

If this issue still persists after using new accounts, `--pokestop-spinning` enabled, and you've made sure your configuration is correct, feel free to comment and we'll reopen the issue.

Make sure to visit our [Discord's #help channel](https://discord.gg/rocketmap) first, because Github is not meant for basic support.
