### ISSUE TITLE
Last_modified missing in gym-details/info webhook

### ISSUE THREAD

**Issue by peterbaumert** [RocketMap/RocketMap#2366]
## Expected Behavior
last_modified field should be sent in the gym-details/info webhook

## Current Behavior
it is not

## Possible Solution
add it :)

## Steps to Reproduce (for bugs)
install Rocketmap and use webhooks

## Context
If you send data so another "service" and the gym webhook gets lost the information of gym-details/info is out of context

## Your Environment
current version

**Comment by sebastienvercammen** [comment]
Gyms have had the `last_modified` field since well over 2 years ago: https://github.com/RocketMap/RocketMap/blob/47c5cae31a702d1a00a1d633ae2187b394ab15bb/pogom/models.py#L116

**Comment by peterbaumert** [comment]
I know but not the gym-details webhook. :)

**Comment by sebastienvercammen** [comment]
@peterbaumert That's intentional, there is no `last_modified` field for the gym details. To send the gym's field with each `gym-details` message would be to send duplicate data, which is not what the webhooks are for.

And if you're looking for a `last_modified` field for the gym's details, the answer is always "now", since otherwise you wouldn't have received a webhook message.
