### ISSUE TITLE
Possible Memory Leak? 

### ISSUE THREAD

**Issue by dpegasusm** [RocketMap/RocketMap#2378]
Currently running a AWS server with 16GB of memory. The map will slowly over time consume all of the available memory until it hits 100% and the OOM killer kills it and it needs to be restarted. 

<img width="1192" alt="screen shot 2017-11-20 at 1 28 26 pm" src="https://user-images.githubusercontent.com/2442680/33035038-c78bbb4c-cdf7-11e7-836c-c41367662fe2.png">

Currently running 4 zones of a map with 500 workers each. each zone is approx 150Km2

## Expected Behavior
Memory will climb until it levels off and then hold relatively constant. 

## Current Behavior
Memory climbs and climbs and climbs

## Steps to Reproduce (for bugs)
1. Running 4 areas of about 150km2 each on an AWS c4.2xl server with 500 workers
2. Any AWS server size seems to have the issue

## Your Environment

* Version used: latest
* Environment name and version (e.g. Python 2.7): Python 2.7.12 
* Operating System and version (desktop or mobile): AWS c4.2xl AMI

**Comment by Kneckter** [comment]
It might be true. I have had this happen over the last week or two where my processes will consume all of the resources until they are shutdown.

My setup is running on Ubuntu 17.04 with 4 step 50s that have 100 workers each. The initial and tth scans have been completed. This is a private machine with a 3.2ghz quad core AMD running 8gb of RAM and a 2gb swap file. 

Before everything is consumed, the cores run at around 80% and 5gb of RAM. Once the swap file is consumed, the python scripts are killed automatically. I setup a bigger swap file for now but that isn't a real solution.

**Comment by friscoMad** [comment]
This usually happens due to queues getting filled, or DB can not process the inserts fast enough or WH can not send them fast enough and both show info in the logs.
I also think this is possible if you change proxies a connection object is stored per proxy and per account until the account is rotated out, that could lead to a lot of objects overtime. Currently there is no solution to this except using -asi to forcefully rotate out accounts.
Also you probably much more accounts than needed for your area, reducing the workers does help a lot in reducing the mem consumption (@dpegasusm )
@Kneckter your setup with 4 instances of 100 workers + probably a webserver instance can use around 4-5Gb, that's not a leak it is just around 450 threads working.
@dpegasusm check also if the mem comsumption does not come from mariaDB, dbs are usually configured to usea a lot of mem, that makes them faster but you need to balance RM and DB memory needs or both will use more than you have.

**Comment by dpegasusm** [comment]
The database is on a separate external server so anything going on here is purely RM and not DB memory/cpu

**Comment by sebastienvercammen** [comment]
@dpegasusm This was made considerably worse by a delayed webhook queue due to a slow receiving webhook server (e.g. PokeAlarm). This has been fixed with #2418.

Were you using webhooks? And have you noticed any change?

**Comment by sebastienvercammen** [comment]
Update to this problem:

Python on Linux doesn't release memory back to the OS. The total memory usage of a Python process can only climb.

We've noticed that this is especially noticeable on `-os` (webserver) instances, and doubly so on higher loads or visitor spikes as the webserver allocates memory to handle the incoming connections and the process' memory usage always stays at the highest point.

> Since Python returns memory to the OS on the heap (that allocates other objects than small objects) only on Windows, if you run on Linux, you can only see the total memory used by your program increase.

http://deeplearning.net/software/theano/tutorial/python-memory-management.html

The above points also still stand (#2418 fixing an infinite queue buildup when using webhooks, DB's memory usage), and more detailed debugging is necessary to confirm the problem.

Since we haven't received a reply from OP in over a week we'll close the issue for now, and leave this comment for reference if anyone encounters the same problem. If @dpegasusm returns, we can also reopen the issue.
