### ISSUE TITLE
Finding TTHs in large stepsize instances is not optimal

### ISSUE THREAD

**Issue by urinella** [RocketMap/RocketMap#2409]
Running a scanner with large -st (e.g. 70 for me) has very low maintenance. Accounts work well together to scan the spawns.
But if you need to rescan your area the TTH search is not optimal.
Accounts are traveling very large distances instead of choosing the nearest account.
Because of that a complete TTH scan needs days or weeks.

The picture is showing the distances accounts travel:

![bildschirmfoto 2017-12-22 um 14 32 25](https://user-images.githubusercontent.com/21242355/34299906-d4039a10-e725-11e7-8ff2-76e2112cda5b.png)

## Expected Behavior

TTH scan is provided by the nearest account to complete it fast.
## Current Behavior

TTH scan is provided by a random account and distances are way too high.
The result is that a full TTH scan needs days or weeks.
## Possible Solution

I don't know what kind of algorithm RM uses. Maybe A*? Because distances are weighted to choose the most optimal account.
This works with spawn-scanning but not with TTH scanning.
Solution could be to weight also the TTH scans.
## Steps to Reproduce (for bugs)

1. Setup a large -st
2. Start an initial scan
3. Wait until 90% of the TTH are detected 
4. See whats happening

**Comment by friscoMad** [comment]
Speed scan internals are a bit complicated but the process is just the inverse, accounts ask for spawn to check and the scheduler returns the scan with the highest priority to each request, priorioty has 3 tiers: bands with fixed top priority, TTHs with fixed mid priority and regular spawns weighted by distance.
Probably for tths and bands some checks could be added to be sure the scan can be done in time but right now that's how it works.
Anyway I am surprised you managed to get such a big instance working I thought the pratical limits for instances were about 50-55 due to python using a single core and scheduler lack of optimization.

**Comment by tomballgithub** [comment]
I am running an ST 80 with geofence without issue, it doesn't need weeks to scan or have a utilization problem

**Comment by sebastienvercammen** [comment]
There are some bottlenecks in the code that make large instances without geofence impractical (sometimes near impossible). Having experimented with setups of step sizes 120 and higher without geofence, the primary issue wasn't the scheduler or the time taken to scan.

Additionally, the SpeedScan algo isn't written to get a minimal walking distance or optimal scan route. It scans items as they come, with a time padding, depending on their priority. This is something that can be looked at in the future, but since the simplest fix is to split it into multiple instances and use geofencing, for now this is not considered an issue.
