### ISSUE TITLE
Exclude Pokemon by Rarity not working with locales

### ISSUE THREAD

**Issue by urinella** [RocketMap/RocketMap#2438]
I noticed that #2387 is not working with locales. I tested -de and -fr. In this case the buttons doing nothing.

I know that there is a Hint inside the PR but this got merged without funcionality, I hope accidentally. Because merging non-funcitonality PRs is a big step backwards...

## Expected Behavior

Pokemon are excluded by rarity.
## Current Behavior

Nothing happens while you are using locales.
## Steps to Reproduce (for bugs)

1. Clone fresh RM
2. Start -os Instance with -L de or -L fr
3. Try to exclude by rarity
4. Nothing happens

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by sebastienvercammen** [comment]
@urinella This was indeed intentional, but it wasn't to merge a step backward for compatibility/localization.

We're working on moving the localization from the back-end (the server) to the front-end (the visitor) so that all UI elements can be properly translated with full support for all features.
