### ISSUE TITLE
We're making way too many pokéstop/gym upserts and causing things to break

### ISSUE THREAD

**Issue by gabrielsoldani** [RocketMap/RocketMap#862]
## Expected Behavior

Pokéstops/gyms should be more conservatively upserted.
## Current Behavior

Even when pulse_radius is set to 70m in search.py, we call get_cells_id with a 1000m radius. The result is every map request returns pokestóps and gyms outside the 70m radius. This is fine and consistent with how the game actually works, but it means every time we scan two locations next to each other, we insert lots of redundant data in the database.

Since #582 was fixed this actually causes an issue on certain occasions: with many db-threads, we may try to REPLACE pokestops we're already REPLACE'ing in another db-thread, causing a ton of mysql deadlocks and filling all the db upsert queues.
## Possible Solution

We call get_cells_id with the appropriate pulse_radius (70m for pokémon, 900m pokéstop/gym-only since #748 was fixed). This is good because Niantic sends less data to us, but is bad because it's inconsistent with how the official client works.

I've implemented this solution and it seems to work fine.
## Steps to Reproduce (for bugs)
1. Run the map.
## Your Environment

Particularly, to run into the deadlock issue, I was running 5 instances with 15 accounts each on one server (-st 10 -sd 10 --db-threads 10), and a database on a different server with about ~150ms latency between the searchers and the database server.

**Comment by justsomedudeonthenet** [comment]
Does this happen with sqlite, mysql or both?  Presumably you are using mysql since you said its on a different server.

One thing that would help is to stop using 'REPLACE INTO'.  It causes rows to be deleted and readded, which causes all the indexes to be recalculated.  Its a fairly expensive SQL command to use.

**Comment by gabrielsoldani** [comment]
I'm using MySQL.

**Comment by gabrielsoldani** [comment]
Woops

**Comment by chuyskywalker** [comment]
Protip: If you run the main app with `-nk -ng` and a second instance with `-np` the first will scan in 70m steps for just pokemons, and the second will scan in 900m steps for just gyms pokestops.

Second, the db will only deadlock like that if running multiple threads (`--db-threads`) -- maaaybe you could turn that back to 1 for a bit. Otherwise we'll have to add a lock.

It's also the ugly, ugly `REPLACE INTO` rearing its head. If that was `INSERT ... ON DUPLICATE KEY UPDATE` this would be a non-issue. :/

**Comment by hemsleyk** [comment]
+1 since this is #748 aware

**Comment by c133** [comment]
@hemsleyk can you go over how to set that up? I am running on a VPS, scan is 25k spawn points, no matter how many workers I throw at it or how much I increase --db-threads the remaining always increases to be too much and server can't keep up.  How do you spread it across containers and divide up the work?

**Comment by hemsleyk** [comment]
I'm using Rancher to manage three VPS (running on a smaller fourth VPS). It's essentially a very, very nice front-end for Docker-Compose.

They have a pre-made Galera (MariaDB) cluster in the catalog incl. load balancing that works quite well. You just aim your pokemongo-map containers at the database load balancer.

**Comment by sebastienvercammen** [comment]
Issue is no longer related to the current codebase (and #748 was merged a long time ago), so we're closing the issue. If anyone still has the problem, please post additional data on latest commit and we'll reopen.
